name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir -p "$HOME/.ssh"
      - run: echo "$GITHUB_DEPLOY_KEY" | tr -d '\r' > "$HOME/.ssh/deploy_key"
      - run: chmod 600 "$HOME/.ssh/deploy_key"
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run: cd dist && rsync -e "ssh -p 22 -i $HOME/.ssh/deploy_key -o StrictHostKeyChecking=no" --archive --compress --delete . lllkojlhuk_ssh@lllkojlhuk.beget.tech:/react-developer-portfolio/public_html